version: '3'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=43.200.51.187:3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=5xfdsw9a
      - DATABASE_NAME=FoodWiki